version: "2"
services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      - REACT_APP_API_URL=https://darkwaters.store:8082
    expose:
       - "80"
    restart: always

  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - PUBLIC_URL=https://darkwaters.store,https://www.darkwaters.store
      - GIN_MODE=release
    volumes:
      - .credentials:/root/.credentials
      - /root/db:/root/db
    expose:
      - "8082"
    restart: always

  reverseproxy:
    container_name: reverseproxy
    depends_on:
        - api
        - web
    build:
      context: .
      dockerfile: proxy/Dockerfile
    volumes:
      - /var/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"