#!/bin/bash

docker-compose -f docker-compose.yaml up -d
docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
docker save --output ~/build_web.tar build_web
docker save --output ~/build_api.tar build_api